SELECT TOP (1000) [QuestionID]
      ,[Source]
      ,[Key]
      ,[Type]
      ,[TypeDetail]
      ,[Question]
      ,[Options]
      ,[MinValue]
      ,[MaxValue]
  FROM [BulletJournalApp].[app].[questions]

-- insert into app.questions
-- select
--      'SpendingPersonal' as [Source]
-- ,'Essential' as [Key]
--     ,'number' as [Type]
--     ,'Money' as [TypeDetail]
-- ,'Essential?' as [Question]
--     ,null as [Options]
--     ,0 as [MinValue]
--     ,null as [MaxValue]
