SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [app].[morning](
	[MorningID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[Date] [date] NOT NULL,
	[GlassOfWater] [bit] NULL,
	[Meds] [bit] NULL,
	[Vitamins] [bit] NULL,
	[Breakfast] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [app].[morning] ADD PRIMARY KEY CLUSTERED 
(
	[MorningID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [app].[morning]  WITH CHECK ADD  CONSTRAINT [FK_morning_User] FOREIGN KEY([UserID])
REFERENCES [app_sys].[user] ([UserID])
GO
ALTER TABLE [app].[morning] CHECK CONSTRAINT [FK_morning_User]
GO
