SELECT TOP (1000) [QuestionID]
      ,[Source]
      ,[Key]
      ,[Type]
      ,[TypeDetail]
      ,[Question]
      ,[Options]
      ,[MinValue]
      ,[MaxValue]
  FROM [BulletJournalApp].[app].[questions]