SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tablePreferencesSetup](
	[TablePreferencesSetupID] [int] IDENTITY(1,1) NOT NULL,
	[TableName] [nvarchar](100) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tablePreferencesSetup] ADD PRIMARY KEY CLUSTERED 
(
	[TablePreferencesSetupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO