SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[timezone](
	[TimezoneID] [int] IDENTITY(1,1) NOT NULL,
	[TimezoneCode] [nvarchar](100) NULL,
	[TimezoneName] [nvarchar](255) NULL,
	[StandardBias] [int] NULL,
	[UTCOffset] [float] NULL,
	[TimezoneBiasID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[timezone] ADD PRIMARY KEY CLUSTERED 
(
	[TimezoneID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
